### ISSUE TITLE
How should we deal with missing values? 

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/fundiversity#1]
Probably discard them but should we display a warning before doing so?

When a value is missing, should we discard the whole row or just ignore this value? What are the implications on the resulting indices (beyond the very practical fact that few datasets will be complete for all traits and species)?

**Comment by Rekyt** [comment]
For the moment we don't test this and neither have implemented it.

**Comment by Rekyt** [comment]
Fixed by 443245f
