### ISSUE TITLE
Improve function efficiency through matrix algebra

### ISSUE THREAD

**Issue by Rekyt** [Bisaloo/fundiversity#11]
I'm pretty sure that the call to `apply()` in `fd_raoq()` could be simplified through matrix algebra:
https://github.com/Bisaloo/fundiversity/blob/1e175ba88531e08242ab9c69b9e470b4cee9e759/R/fd_raoq.R#L60-L62

**Comment by Bisaloo** [comment]
```r
diag(sp_com %*% tcrossprod(dist_matrix, sp_com))
```

Now, an interesting question is trying to understand what values outside of the diagonal mean :thinking:

**Comment by Bisaloo** [comment]
|expr                                                       |      min|       lq|     mean|   median|       uq|        max| neval|
|:----------------------------------------------------------|--------:|--------:|--------:|--------:|--------:|----------:|-----:|
|fd_raoq(traits = traits_birds, sp_com = site_sp_birds)     | 1.119820| 1.167955| 1.577048| 1.207574| 1.300485|   8.713098|  1000|
|fd_raoq_old(traits = traits_birds, sp_com = site_sp_birds) | 2.045435| 2.100812| 3.159528| 2.160546| 2.357134| 100.263167|  1000|

**Comment by Bisaloo** [comment]
Fixed by https://github.com/Bisaloo/fundiversity/commit/5240f08e439151aec9841397d482b677654dd04a.
