### ISSUE TITLE
Parallel computation of functional diversity indices

### ISSUE THREAD

**Issue by Rekyt** [Bisaloo/fundiversity#13]
From the performance vignette #8  we can see that some indices can take while to compute with big matrices.
One interesting (but certainly expansive development-wise) feature would be to allow for automatic parallel computation of functional diversity indices across sites through the split of the site-species matrix in chunks.
The implementation could use the `future` package.

**Comment by Bisaloo** [comment]
This is actually very easy. If you think, it's worth it, I can implement it very soon.

**Comment by Rekyt** [comment]
A specific vignette could explain how to setup parallel computation of functional diversity indices and what are the performance gain to know when it is worth it to parallelize.
Maybe comparing `future.scheduling` parameters in [`future_lapply()`](https://www.rdocumentation.org/packages/future.apply/versions/1.7.0/topics/future_apply)

**Comment by Bisaloo** [comment]
As far as I can tell, we don't expect the different iterations of the `(future_)apply()` loop to vary a lot in their execution time so we should keep the default for `future.scheduling`.

> Q. What about load balancing?
A. The default behavior of all functions is to distribute equally-sized chunks of elements to each available background worker - such that each worker process exactly one chunk (= one future). If the processing times vary significantly across chunks, you can increase the average number of chunks processed by each worker, e.g. to have them process two chunks on average, specify future.scheduling = 2.0. Alternatively, you can specify the number of elements processed per chunk, e.g. future.chunk.size = 10L (an analog to the chunk.size argument added to the parallel package in R 3.5.0).

From https://www.jottr.org/2018/06/23/future.apply_1.0.0/

**Comment by Rekyt** [comment]
I was thinking about the fact that single site functional diversity index computation may go really fast. So if we parallelize across sites.
Wouldn't it creates a burden in this case?
I'm unsure about how `future` handles that, so I was thinking about grouping computation with several sites.
