### ISSUE TITLE
FDiv is computed on the vertices of the convex hull

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/fundiversity#15]
FDiv is computed on the vertices of the convex hull formed by the data points, not on the entirety of the points.

This means we have to compute the convex hull even in the FDiv.

This might cause quite a performance hit so it might be interesting to think about caching the result of `convhulln()` to avoid unnecessary re-computation when getting both FRic and FDiv. This is likely the role of `verts.txt` in FD.

**Comment by Rekyt** [comment]
We could try using `memoise` to cache the`convhulln()` when computed in `fd_fric()` and then call it in `fd_fdiv()`
