### ISSUE TITLE
Do not compute convex hulls on each row separately 

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/fundiversity#17]
A naive implementation to compute FRic is to compute the convex hull for each row separately.

However, this problem can be simplified since each row is a subset of the entire species list. The various convex hulls are not computed on completely independent points but on a subset / the union / etc. of points for which we previously computed the convex hull.

**Comment by Bisaloo** [comment]
https://en.wikipedia.org/wiki/Dynamic_convex_hull

**Comment by Bisaloo** [comment]
A simple first approach could be to identify all the rows/sites that will lead to the same convex hulls by eliminating the points that cannot be vertices using the Akl-Toussaint heuristic. From [Wikipedia](https://en.wikipedia.org/wiki/Convex_hull_algorithms#Akl%E2%80%93Toussaint_heuristic):

> ### Akl–Toussaint heuristic
>
> The following simple heuristic is often used as the first step in implementations of convex hull algorithms to improve their performance. It is based on the efficient convex hull algorithm by Selim Akl and G. T. Toussaint, 1978. The idea is to quickly exclude many points that would not be part of the convex hull anyway. This method is based on the following idea. Find the two points with the lowest and highest x-coordinates, and the two points with the lowest and highest y-coordinates. (Each of these operations takes O(n).) These four points form a convex quadrilateral, and all points that lie in this quadrilateral (except for the four initially chosen vertices) are not part of the convex hull. Finding all of these points that lie in this quadrilateral is also O(n), and thus, the entire operation is O(n). Optionally, the points with smallest and largest sums of x- and y-coordinates as well as those with smallest and largest differences of x- and y-coordinates can also be added to the quadrilateral, thus forming an irregular convex octagon, whose insides can be safely discarded. If the points are random variables, then for a narrow but commonly encountered class of probability density functions, this throw-away pre-processing step will make a convex hull algorithm run in linear expected time, even if the worst-case complexity of the convex hull algorithm is quadratic in n.

**Comment by Bisaloo** [comment]
https://codeforces.com/blog/entry/75929

**Comment by Rekyt** [comment]
See G. S. Brodal and R. Jacob, "Dynamic planar convex hull," The 43rd Annual IEEE Symposium on Foundations of Computer Science, 2002. Proceedings., Vancouver, BC, 2002, pp. 617-626, doi: https://doi.org/10.1109/SFCS.2002.1181985.
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1181985

The author proposed a data structure that may help to dynamically search convex hulls for nested sets of points.

**Comment by Rekyt** [comment]
From a practical perspective, it seems we're lacking the tool to implement such ideas. Even if it makes computational sense, there are no existing R packages offering computation of dynamic convex hulls.

We also do not have the time, the skills, or the people to work on such detailed implementation.
So closing this issue for now.
