### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by Rekyt** [Bisaloo/fundiversity#4]
In order to show the interest of having another package to compute functional diversity indices, we should also make a vignette that shows performance comparison between `fundiversity` and related packages.

**Comment by Bisaloo** [comment]
Slightly adapted from https://github.com/Bisaloo/fundiversity/issues/3#issuecomment-731226062 to try to have a fair comparison:

``` r
# Comparing Rao's Quadratic Entropy results

library(fundiversity)

data("traits_birds")

site_sp <- matrix(1/nrow(traits_birds), ncol = nrow(traits_birds))
rownames(site_sp) <- "s1"
colnames(site_sp) <- rownames(traits_birds)

dist_traits_birds <- dist(traits_birds)

suppressPackageStartupMessages(library(adiv))
library(hillR)
library(SYNCSA)

library(magrittr)

microbenchmark::microbenchmark(
  { fd_raoq(traits = NULL, site_sp, dist_traits_birds) },
  { QE(site_sp, dis = dist_traits_birds) },
  { hill_func(site_sp, dist_traits_birds, traits_as_is = TRUE)[1, ] },
  { rao.diversity(site_sp, phylodist = as.matrix(dist_traits_birds), standardize = FALSE)$PhyRao }
) %>%
  summary() %>%
  knitr::kable()
```

<table style="width:100%;">
<colgroup>
<col style="width: 61%" />
<col style="width: 5%" />
<col style="width: 6%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 6%" />
<col style="width: 3%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">expr</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">lq</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">uq</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">neval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">{ fd_raoq(traits = NULL, site_sp, dist_traits_birds) }</td>
<td style="text-align: right;">804.089</td>
<td style="text-align: right;">938.5345</td>
<td style="text-align: right;">1365.666</td>
<td style="text-align: right;">1036.433</td>
<td style="text-align: right;">1196.289</td>
<td style="text-align: right;">8114.275</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">{ QE(site_sp, dis = dist_traits_birds) }</td>
<td style="text-align: right;">1417.735</td>
<td style="text-align: right;">1572.6415</td>
<td style="text-align: right;">2652.666</td>
<td style="text-align: right;">1707.608</td>
<td style="text-align: right;">2028.277</td>
<td style="text-align: right;">25217.204</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">{ hill_func(site_sp, dist_traits_birds, traits_as_is = TRUE)[1, ] }</td>
<td style="text-align: right;">18585.503</td>
<td style="text-align: right;">19524.3515</td>
<td style="text-align: right;">21731.890</td>
<td style="text-align: right;">20070.883</td>
<td style="text-align: right;">24635.533</td>
<td style="text-align: right;">37069.860</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">{ rao.diversity(site_sp, phylodist = as.matrix(dist_traits_birds), standardize = FALSE)$PhyRao }</td>
<td style="text-align: right;">70237.335</td>
<td style="text-align: right;">74890.4175</td>
<td style="text-align: right;">82561.233</td>
<td style="text-align: right;">77826.702</td>
<td style="text-align: right;">83106.498</td>
<td style="text-align: right;">356309.332</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Bisaloo** [comment]
Importantly, the difference increases with the number of sites:

``` r
# Comparing Rao's Quadratic Entropy results

library(fundiversity)

data("traits_birds")

site_sp <- matrix(1/nrow(traits_birds), ncol = nrow(traits_birds), nrow = 10)
rownames(site_sp) <- paste0("s", 1:10)
colnames(site_sp) <- rownames(traits_birds)

dist_traits_birds <- dist(traits_birds)

suppressPackageStartupMessages(library(adiv))
library(hillR)
library(SYNCSA)

library(magrittr)

microbenchmark::microbenchmark(
  { fd_raoq(traits = NULL, site_sp, dist_traits_birds) },
  { QE(site_sp, dis = dist_traits_birds) },
  { hill_func(site_sp, dist_traits_birds, traits_as_is = TRUE)[1, ] },
  { rao.diversity(site_sp, phylodist = as.matrix(dist_traits_birds), standardize = FALSE)$PhyRao },
  times = 1000
) %>%
  summary() %>%
  knitr::kable()
```

<table>
<colgroup>
<col style="width: 62%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 3%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">expr</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">lq</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">uq</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">neval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">{ fd_raoq(traits = NULL, site_sp, dist_traits_birds) }</td>
<td style="text-align: right;">2.179250</td>
<td style="text-align: right;">2.381283</td>
<td style="text-align: right;">3.889422</td>
<td style="text-align: right;">2.556197</td>
<td style="text-align: right;">2.867067</td>
<td style="text-align: right;">261.5314</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="even">
<td style="text-align: left;">{ QE(site_sp, dis = dist_traits_birds) }</td>
<td style="text-align: right;">6.370308</td>
<td style="text-align: right;">7.120387</td>
<td style="text-align: right;">11.229153</td>
<td style="text-align: right;">8.796693</td>
<td style="text-align: right;">12.383851</td>
<td style="text-align: right;">268.7088</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">{ hill_func(site_sp, dist_traits_birds, traits_as_is = TRUE)[1, ] }</td>
<td style="text-align: right;">26.535204</td>
<td style="text-align: right;">28.221553</td>
<td style="text-align: right;">32.178247</td>
<td style="text-align: right;">31.994512</td>
<td style="text-align: right;">33.737498</td>
<td style="text-align: right;">289.3393</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="even">
<td style="text-align: left;">{ rao.diversity(site_sp, phylodist = as.matrix(dist_traits_birds), standardize = FALSE)$PhyRao }</td>
<td style="text-align: right;">72.419072</td>
<td style="text-align: right;">76.003354</td>
<td style="text-align: right;">80.143180</td>
<td style="text-align: right;">79.166810</td>
<td style="text-align: right;">82.418401</td>
<td style="text-align: right;">335.8404</td>
<td style="text-align: right;">1000</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
