### ISSUE TITLE
Investigate RCGAL as a replacement of geometry

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/fundiversity#45]
https://github.com/stla/RCGAL

I have not tested anything yet.

Would need to:

- wait until it's on CRAN
- evaluate the performance vs geometry

Downside:

- has more imports but that might be discussed with the developer(?)

**Comment by Rekyt** [comment]
Good idea, however it seems it only works in the special cases of 2D and 3D https://github.com/stla/RCGAL/blob/main/R/convexhull.R#L34

**Comment by Bisaloo** [comment]
Ah right, good point. I should have read more before posting.

**Comment by Rekyt** [comment]
But maybe it's a good alternative to consider for these cases!

**Comment by Rekyt** [comment]
Closing for now unless we have clear evidence of a better performance of convex hull computation in a general case.

Maybe if performance is astonishingly good in 2D or 3D cases it would be worth implementing.
