### ISSUE TITLE
Simplify CI matrix by using `_R_CHECK_DEPENDS_ONLY_TESTS_`

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/fundiversity#47]
Since R 4.1.3, we can run tests without packages from `Suggests` by setting the `_R_CHECK_DEPENDS_ONLY_TESTS_` env var to `true`.

https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#index-_005fR_005fCHECK_005fDEPENDS_005fONLY_005fTESTS_005f

**Comment by Bisaloo** [comment]
This should stay open until R 4.1.3 is out and we can set `_R_CHECK_DEPENDS_ONLY_TESTS_`

**Comment by Rekyt** [comment]
oopsie!
