### ISSUE TITLE
Site name when no site-species matrix is provided

### ISSUE THREAD

**Issue by Rekyt** [Bisaloo/fundiversity#9]
When no site-species matrix is provided, the site is called "s1" should it be called something else?
Also the row.names is then "s1" this should probably be set to NULL to avoid confusion:
``` r
fundiversity::fd_fric(fundiversity::traits_birds)
#>    site     FRic
#> s1   s1 230967.7
```

<sup>Created on 2020-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Rekyt** [comment]
It is the case for `fd_fric()` and for `fd_fdiv()` but not for `fd_raoq()`:
``` r
fundiversity::fd_fric(fundiversity::traits_birds)
#>    site     FRic
#> s1   s1 230967.7
fundiversity::fd_fdiv(fundiversity::traits_birds)
#>    site      FDiv
#> s1   s1 0.6011971
fundiversity::fd_raoq(fundiversity::traits_birds)
#>   site        Q
#> 1   s1 170.0519
```

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Bisaloo** [comment]
Should we also set `stringAsFactors = FALSE` to ensure consistent output between R < 4.0 and R >= 4.0?
